framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    trusted_headers: ['x-forwarded-for', 'x-forwarded-port', 'x-forwarded-proto']
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    session:
        handler_id: null
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: session.storage.factory.native

    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system

    assets:
        enabled: true
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

when@dev:
    framework:
        profiler:
            enabled: true
        ide: '%env(IDE)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        session:
            cookie_secure: true