framework:
    notifier:
        chatter_transports: [] # Aucun transport de chat configuré
        texter_transports: []  # Aucun transport de SMS configuré

        channel_policy:
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']

        admin_recipients:
            - { email: admin@aktibat.fr }
