twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - 'form_div_layout.html.twig'
        - 'bootstrap_5_layout.html.twig'

    date:
        format: 'd/m/Y'
        interval_format: '%%d jours'
        timezone: '%env(TZ)%'

    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '

    globals:
        app_name: '%env(APP_NAME)%'
        current_year: '%env(CURRENT_YEAR)%'
        app_version: '1.0.0'
        google_analytics_id: '%env(GA_ID)%'

    paths:
        '%kernel.project_dir%/vendor/symfony/twig-bridge/Resources/views/Form': ~

    # Gestiondes erreurs 403.html.twig, 404.html.twig, 500.html.twig, 
    exception_controller: null

when@test:
    twig:
        strict_variables: true
