<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_DEBUG' => '0',
  'APP_SECRET' => '851c4566d8d84d2a3f8d4d61352dac4a75a2c4e527fea4e4301b691d0b2fc0ab',
  'APP_NAME' => 'Aktibat',
  'APP_DOMAIN' => 'aktibat.fr',
  'CURRENT_YEAR' => '2025',
  'TZ' => 'Europe/Paris',
  'IDE' => 'phpstorm',
  'DATABASE_URL' => 'DATABASE_URL="mysql://scligrw8287_aktibat-scligrw8287:AktiBat_41240-2005X10@127.0.0.1:3306/scligrw8287_aktibat1?serverVersion=10.6.22-MariaDB&charset=utf8mb4"',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default',
  'MAILER_DSN' => 'smtp://mail.aktibat.fr:465?encryption=ssl&auth_mode=login',
  'MAILER_FROM' => 'noreply@aktibat.fr',
  'MAILER_CONTACT' => 'contact@aktibat.fr',
  'MAILER_SENDER_NAME' => 'Aktibat',
  'UPLOADS_BLOG_DIR' => '%kernel.project_dir%/public/uploads/blog',
  'UPLOADS_GALLERY_DIR' => '%kernel.project_dir%/public/uploads/gallery',
  'UPLOADS_MAX_SIZE' => '4M',
  'GA_ID' => 'G-3HM7T2VRQL',
  'TRUSTED_PROXIES' => '127.0.0.1,localhost',
  'LOCK_DSN' => 'flock',
  'REDIS_HOST' => '127.0.0.1',
  'REDIS_PORT' => '6379',
);
